### ISSUE TITLE
Create static section enhancement

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#16]
- [x]  Remove the option to add a new section type
- [x] Add a variable in the file where the section is declared that will list the media fields to be added too
- [ ] When clicking on the add new section option, in the listing of available sections add the non available one grayed out with a toggle in the top left with Label Create ( Créer in french)
- [x] When enabling the  toggle the section type is created with the fields available in the variable mentioned in point 2 and take the actual design with the bin icon to delete it, and the toggle is hidden, of course when I delete the section it is back grayed out with the toggl

**Acceptance testing**

- [x]  Remove the option to add a new section type
- [x] Add a variable in the file where the section is declared that will list the media fields to be added too
- [x] When clicking on the add new section option, in the listing of available sections add the non available one grayed out with a toggle in the top left
- [x] When enabling the  toggle the section type is created with the fields available in the variable mentioned in point 2 and take the actual design with the bin icon to delete it, and the toggle is hidden, of course when I delete the section it is back grayed out with the toggle

**Comment by mahfouzhseineweev** [comment]
@akramsarkis I didn't get the first and the last point

**Comment by mahfouzhseineweev** [comment]
I don't think the first point is feasible because in the source code, the media fields name will depend on the dev that is declaring these names and the format that He is using, so it is not possible to track the field names of media separately

**Comment by jfayad** [comment]
@mahfouzhseineweev 
> I don't think the first point is feasible because in the source code, the media fields name will depend on the dev that is declaring these names and the format that He is using, so it is not possible to track the field names of media separately

I'm not getting your comment here and I don't see why you think point 1 is not feasible...

**Comment by mahfouzhseineweev** [comment]
@jfayad I think it is not feasible because it is not possible to detect where this media field name is located at inside the components options as it will vary based on the section needs.

We can solve this by making a separate prop in the section view component that will have the media field names array

```
[
{
type: 'image',
name: 'media',
sectionTypeName: 'TextImage'
.
.
.
}
]
```

Then in the sections main component of the library, we read this array if it exists and we add the field names to the section  to be created if the `sectionTypeName` match the section type selected in the form

**Comment by mahfouzhseineweev** [comment]
The creator of the section knows where the media fields name are located but the library doesn't know as the media field name location inside the options is arbitrary and it will differ from a section to another.

So for the library to know these media field names, it must know first where they are located inside the options which is not possible and for that the creator of the section must add a separate prop with the media field names He wants to declare per section. And then the library, when selecting a section type from the dropdown list, it will read this prop of the selected section type and populate the media field names inside the create section type form as non editable inputs.

**Comment by jfayad** [comment]
the idea is to have a declaration of the field that will contain its name AND its type. The library won't have to guess anything, it will be explicitly declared...

**Comment by mahfouzhseineweev** [comment]
> The library won't have to guess anything, it will be explicitly declared

@jfayad I think I got confused by the issue, as it is stating that we need to remove all the fields and so the Media fields name should be pre-populated in the form. And when you say that they should be explicitly declared, you mean that the admin should still input the field name of the media in the form. Because otherwise the library can not guess when in the section form settings the media field is placed to get its name and show it pre-populated when selecting the section type from the list.

<img width="923" alt="Screenshot 2023-11-21 at 9 14 02 AM" src="https://github.com/Geeks-Solutions/nuxt-sections/assets/101403093/1bcc6cd3-c923-4898-a4e0-07b86fa13c69">

**Comment by akramsarkis** [comment]
I updated the description regarding the following discussion on Matttermost https://mattermost.gl.eweev.com/eweev/pl/1ckzubnp77dabkyr7mgx9nguba

**Comment by akramsarkis** [comment]
all good , closing
