### ISSUE TITLE
Query string management through the page settings

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#37]
- [ ] Query string management through the page settings
- Query string must be required
- We must have an informative message to explain the user how it works
- We should show how the url will show after adding the query strings

**Acceptance testing**

- [ ] @mahfouzhseineweev I need you here regarding how you will manage it

**Comment by akramsarkis** [comment]
@mahfouzhseineweev please to update the description of the issue if it is needed and to let me know what are the acceptance testing I need to add

**Comment by mahfouzhseineweev** [comment]
### Report Summary of peer session with Julien:

* QSs will be added to the Page path inside the page settings and it will have the following format:

`/test/qs-{title}/qs-{categories_titles}`

Then what I do in the front side is to split `/qs-`, send path as `/test` and in metadata object I store the query string keys in array like this:

```
query_string_keys: {
0: 'title',
1: 'categories_titles'
}
```

* When requesting in the url a page like: `/test/qs-Article 3/qs-Science,People`

I also split the `/qs-` so the page path will be the first one `/test`, the `title` will be the second one `Article 3` and the `categories_titles` will be the third one `Science,People` so that **title** and **categories_titles** can be sent as the query_strings


* On the Blogs BO that we will have, we will be adding an **article_path** field that will hold the full path of the article we are creating ex.: `article_path = '/test/qs-Article 3/qs-Science,People'` which will help us to make the redirections from the list of Articles to display a full articles

**Comment by akramsarkis** [comment]
@mahfouzhseineweev i have some questions:

1- So in the page settings , there will fields specific to the query strings that I can fill, correct ?
2- If 1 is correct, what if I fill in only one of the query strings and not the other ?
3- I suppose those query strings will be optional correct ?
4- I did not get the last point about the path , Julien said that we will add for the article in a blog a new field path; but in your example you are showing it including the page url ( / test) , but when we will create an article in blogs we won't know in which page it will be so, I am a bit confused

**Comment by mahfouzhseineweev** [comment]
### Report after Peer Session with Julien:

The decision taken to solve the QS issue we have is the following:

* There is no more need to add the QS keys in the page settings anymore

* We will have the QS in the URL detected by having the `=` character, so `QSKey=QSValue` and the order of them will not matter

ex.: `/test/title=Article 3/categories_titles=Science,People`. In this example QS are the ones that has = separator so `title that is Article 3 and categories_titles that is Science,People`, and pagePath is `/test`

**Comment by akramsarkis** [comment]
Closing this issue that is no more valid
