### ISSUE TITLE
Offset adjustment for the categories articles section

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#54]
- [ ] You need to use offset_ca as offset and to send it 0 without adding it in the url

**Acceptance testing**

- [ ] You need to use offset_ca as offset and to send it 0 without adding it in the url

**Comment by mahfouzhseineweev** [comment]
Hello @jfayad Akram informed me that it wont be possible on backend to default the offset to zero. 
But for the update on the library, I think this issue is not describing the correct update needed.

There two possible solutions we can do one is on the host project and the other is on library:

* Host: We simply send this query string in the url with its default value `offset_ca=0`
* Library: We make an update on QSs management to send a default value 0 to all QSs that are prefixed with `offset`

Which one should it be ?

**Comment by jfayad** [comment]
@mahfouzhseineweev the offset defaulting to 0 is specific to the host project and we shouldn't have such a custom management leak into the library.

**Comment by akramsarkis** [comment]
Closing this one as it is not in the library
